### ISSUE TITLE
Vector3dVector function slow

### ISSUE THREAD

**Issue by VinceDT** [IntelVCL/Open3D#403] opened 2018-06-21 10:31 UTC
Thanks for this  great library. 
I am using the Vector3dVector function to convert my numpy array of about 200.000 points of xyz rgb data to open3d. The functions takes about 200 ms for setting the points and the colors each. Is there any reason for this quite slow operation or anything I can do about it?

**Comment by qianyizh** [comment] 2018-06-22 08:53
Yeah it is slow. This is annoying.
```
import open3d
import numpy as np
x = np.random.random((200000,3))
y = open3d.Vector3dVector(x)
```
Takes around 100ms. Strange thing is, I tested it on a very old version of Open3D and it is blazing fast.
And it should not be slow. Under the hood it is pybind11's buffer_protocol, which should be a barebone access to the memory buffer.

We need more time to investigate.

**Comment by argosvr** [comment] 2018-07-26 14:40
hello... we encounter the same problem trying to visualize in realtime a PC. But Vector3dVector  is really far to slow to do something workable.

**Comment by syncle** [comment] 2018-07-30 16:47
I found some clue. 
Before this PR https://github.com/IntelVCL/Open3D/pull/127, the following code:
```
import numpy as np
import time

class Timer(object):
    def __init__(self, name=None):
        self.name = name

    def __enter__(self):
        self.tstart = time.time()

    def __exit__(self, type, value, traceback):
        if self.name:
            print('[%s]' % self.name)
        print('Elapsed: %.3f' % (time.time() - self.tstart))

with Timer("Test Vector3dVector"):
    x = np.random.random((2000000,3))
    y = Vector3dVector(x)
```
outputs:
```
[Test Vector3dVector]
Elapsed: 0.398
```
but after the PR https://github.com/IntelVCL/Open3D/pull/127, it become
```
[Test Vector3dVector]
Elapsed: 2.114
```

However, I haven't found a solution yet. The main purpose PR was to upgrade pybind 2.0 to 2.2. I have compared [commits](https://github.com/IntelVCL/Open3D/commit/331aa50c90df0c9db9888f484d4b63b6b1e98cf5#diff-670baec744fd6ddd565595df4cdca365) between before and after this PR, but src/Python/py3d.h and src/Python/py3d_eigen.cpp are untouched. I think python binding of open3d need to be [optimized in accordance with pybind 2.2](http://pybind11.readthedocs.io/en/stable/upgrade.html).

**Comment by qianyizh** [comment] 2018-07-31 03:09
Is there anyway we can identify it is a problem of pybind11 2.2 or it's a problem of our implementation? If it is a pybind11 2.2 issue, we should try their latest version or file a bug report on their repo.

**Comment by argosvr** [comment] 2018-08-01 09:30
Well, for us vector3dvector is a core feature of open3d. We work a lot with numpies. Not only for visualization but also for example to send realtime scan streams over tcpip to a server.
At that time, it is almost impossible, it is to slow.
Then it would be nice if this issue could be solved.

**Comment by syncle** [comment] 2018-08-02 16:51
Some updates. 
- The issue persists even I tried with the recent pybind 2.2.3
- Our code for binding seems fine, and I cannot find relevant issue or documents from pybind11
- I opened a ticket for this issue in official pybind11 repo: https://github.com/pybind/pybind11/issues/1481

**Comment by richipower** [comment] 2018-10-25 14:42
Hi!, are there some news on this issue?

**Comment by qianyizh** [comment] 2018-10-26 04:12
The ticket on pybind11 is still hanging: pybind/pybind11#1481
Does anyone have a direct connection with the pybind11 team and can help us ping them?

**Comment by qianyizh** [comment] 2018-10-30 07:28
Update:

We have heard back from Wenzel. The root cause is that we are casting a large vector of small vectors (std::vector<Eigen::Vector3d>) to python. (The new version of) Pybind11 does checks for all these casts to try to avoid copy.  So in our case pybind11 does lots of checks which drag the performance down.

There are a couple of workarounds that can help this. We are looking into them and trying to find the best solution asap.

**Comment by qianyizh** [comment] 2018-11-02 16:05
For people who are following this thread, @yxlao made the fix in #657 . I am reviewing it and hopefully will merge it into master during the weekend. Please test it out and let us know if this addresses the performance issue for you.

**Comment by richipower** [comment] 2018-11-03 10:50
Thank you for the support! i will test it in the weekend :)

**Comment by richipower** [comment] 2018-11-05 09:21
can we directly install the new version through anaconda? with pip install open3d? or should we build the new version from source?

**Comment by yxlao** [comment] 2018-11-05 17:58
before the next release, we'll need to build from source to get the latest version

**Comment by syncle** [comment] 2018-12-17 19:19
Addressed in #657. @VinceDT @argosvr @richipower: Please check :)

**Closed by syncle** 2018-12-17 19:19 UTC
Labels: enhancement, high priority

**Comment by heethesh** [comment] 2020-09-03 00:34
When using numpy with `Vector3dVector`, I noticed a slow down with the visualization when the numpy array type was `np.float32`. Initializing my array with `dtype=np.float64` (which is the default type I think), solved it for me!

**Comment by Chris10M** [comment] 2022-11-15 11:35
On same note as @heethesh, the hot fix is to use  `dtype=np.float64` for `Vector3dVector` and `dtype=np.int32` for `Vector3iVector`.

**Comment by GipsonLeo** [comment] 2024-02-21 11:19
> When using numpy with `Vector3dVector`, I noticed a slow down with the visualization when the numpy array type was `np.float32`. Initializing my array with `dtype=np.float64` (which is the default type I think), solved it for me!

np.float64, it works for me
