### ISSUE TITLE
Rendering problem?

### ISSUE THREAD

**Issue by martinakos** [IntelVCL/Open3D#541] opened 2018-09-06 10:23 UTC
I've been testing UniformTSDFVolume to fuse point clouds of an object I want to model. After integrating  point clouds for a while I can display the tsdf surface point cloud with this code:

```
pcd = builder.tsdf.extract_point_cloud()
o3d.draw_geometries([pcd])
```

and I get this rendering:
![image](https://user-images.githubusercontent.com/2371869/45150101-fe1ec000-b1c2-11e8-8bac-ab684c90c230.png)
which looks fine. 

However, I want to show the tsdf point cloud as it is being collected and for that I render it using the following non-blocking approach:
```
        pcd = builder.tsdf.extract_point_cloud()
        vis.add_geometry(pcd)
        ctr = vis.get_view_control()
        w_Rt_o = pinv(w_Rt_c) @ builder.w_tsdf_Rt_o
        ctr.convert_from_pinhole_camera_parameters(builder.intrinsics, w_Rt_o)
        im = (np.asarray(vis.capture_screen_float_buffer(True)) * 255).astype(np.uint8) 
        plt.figure("im")
        plt.imshow(im)
```

vis is created like this:

```
    vis = o3d.Visualizer()
    vis.create_window(width=640, height=480)  
```
The code related with convert_from_pinhole_camera_parameters is to set the view point according to my current view of the object.

Then I can see in the matplotlib window how the tsdf is being created without blocking the process. However, if I show the figure after having integrated the same number of point clouds into the tsdf as in the figure above I get:

![image](https://user-images.githubusercontent.com/2371869/45151261-bcdbdf80-b1c5-11e8-87c4-50c2679b75d2.png)

which looks wrong and a lot more noisy.  

I have been playing with the vis.get_render_option() and loading a renderoption.json file, then changing some of the parameters in the file but I can't get it to look the same as when I use o3d.draw_geometries([pcd]).  Why does this happen and What can I do to get the same visualisation as with draw_geometries?

**Comment by qianyizh** [comment] 2018-09-07 08:48
I think the problem is with ``vis.add_geometry(pcd)``. This function does what it literally means: adds a geometry to the visualizer. So in your loop, you keep adding partially created point clouds into the visualizer, and ends up with hundreds of point cloud rendered together. Hence you observe the noise.

What you should do is to call ``vis.add_geometry(pcd)`` once before the loop. Then in the loop, you update ``pcd``, then call ``vis.update_geometry()``. Very much like this tutorial:
http://www.open3d.org/docs/tutorial/Advanced/non_blocking_visualization.html#initialize-visualizer-class

Hope this helps.

**Comment by martinakos** [comment] 2018-09-07 09:57
Ok, thanks! that was it. 
I solved it by calling vis.add_geometry(pcd) once only and then just updating the pcd.points, pcd.normals, and pcd.colors with the newly extracted point clouds and calling  vis.update_geometry().

**Comment by qianyizh** [comment] 2018-09-07 15:55
Close this issue since there is a solution. Feel free to reopen it.

**Closed by qianyizh** 2018-09-07 15:55 UTC

**Comment by uros171513** [comment] 2019-05-29 06:34
@martinakos How did you fuse multiple different point clouds into one?
