### ISSUE TITLE
Does not seem to provide c + + interface

### ISSUE THREAD

**Issue by QinZiwen** [IntelVCL/Open3D#140] opened 2018-02-08 06:28 UTC
Open3D is a very nice open source tool, But it does not seem to provide c + + interface.

**Comment by syncle** [comment] 2018-02-08 06:49
Nope. Please see #130.

**Comment by qianyizh** [comment] 2018-02-08 08:14
Close the ticket since it is a duplicate of #130

**Closed by qianyizh** 2018-02-08 08:14 UTC
