### ISSUE TITLE
Visualizer::CreateWindow confliction problem

### ISSUE THREAD

**Issue by dotchang** [IntelVCL/Open3D#422] opened 2018-06-29 05:18 UTC
On windows MSVC environment, the name of CreateWindow is defined by windows.h which is basic library by microsoft. (I think it's terrible, but...)
When I tried to use Open3D and other windows software, it makes name confliction problem.

Could you please consider changing the name?

**Comment by syncle** [comment] 2018-07-02 02:45
I may misunderstood the point, but Visualizer::CreateWindow() is the function of Visualizer class. Is this naming conflict making some technical issue (such as compilation error)?

**Comment by dotchang** [comment] 2018-07-02 04:29
WinUser.h which is a part of WindowsSDK10 of the microsoft gives a global definition as follows, 
(line 4283)
#ifdef UNICODE
#define CreateWindow  CreateWindowW
#else
#define CreateWindow  CreateWindowA
#endif // !UNICODE

Then, it makes problems. Do you have good solutions?

**Comment by qianyizh** [comment] 2018-07-03 17:05
Did this happen when you are compiling Open3D or when you are compiling an external C++ program that is linked to Open3D?

**Comment by dotchang** [comment] 2018-07-04 03:35
It happened when I tried to use external C++ program.
I want to use Open3D with openFrameworks.

**Comment by qianyizh** [comment] 2018-07-05 04:57
Umm, I think I understand this now.

I remember a long time ago ``three::filesystem::MakeDirectory()`` was named ``three::filesystem::CreateDirectory()``, then it conflicts with Windows' ``CreateDirectory`` which is a macro mask of ``CreateDirectoryA`` or ``CreateDirectoryW`` (yes, terrible design, but...). I looked for workarounds and eventually decided to change the function name.
https://github.com/IntelVCL/Open3D/blob/dd511a0d3f973735d15ae9b90e292077886f1e1b/src/Core/Utility/FileSystem.h#L52

I think ``three::Visualizer::CreateWindow`` is the same case. Let me hot fix it.

**Comment by qianyizh** [comment] 2018-07-05 04:59
@syncle to explain it a bit more, the problem is with the macro definition. C++ macro overrides everything. So once a windows header file is included the macro overrides all the valid function names. In a cpp file that uses ``three::filesystem::CreateDirectory()``, it is translated into ``three::filesystem::CreateDirectoryA()`` or ``three::filesystem::CreateDirectoryW()``, which breaks the build.

**Comment by syncle** [comment] 2018-07-05 07:37
Addressed in #433.

**Closed by syncle** 2018-07-05 07:37 UTC
Labels: assigned, bug
