### ISSUE TITLE
`visibility=hidden` prevents shared libraries compilation

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#295] opened 2018-04-12 07:31 UTC
The `CMAKE_CXX_FLAGS` flag in the `src/CMakeLists.txt` file has an argument `-fvisibility=hidden`  for Mac.
This [causes a failure when building shared libraries](https://travis-ci.org/IntelVCL/Open3D/jobs/365457217).. When this is removed, [Mac build properly](https://travis-ci.org/IntelVCL/Open3D/jobs/365472768).

While this has some relation with `pybind11` as per your documentation ([advanced](https://github.com/IntelVCL/Open3D/blob/331aa50c90df0c9db9888f484d4b63b6b1e98cf5/src/External/pybind11/docs/advanced/misc.rst#partitioning-code-over-multiple-extension-modules), [benchmark](https://github.com/IntelVCL/Open3D/blob/331aa50c90df0c9db9888f484d4b63b6b1e98cf5/src/External/pybind11/docs/benchmark.rst#setup), [FAQ](https://github.com/IntelVCL/Open3D/blob/331aa50c90df0c9db9888f484d4b63b6b1e98cf5/src/External/pybind11/docs/faq.rst#someclass-declared-with-greater-visibility-than-the-type-of-its-field-someclassmember--wattributes), and [upgrade](https://github.com/IntelVCL/Open3D/blob/331aa50c90df0c9db9888f484d4b63b6b1e98cf5/src/External/pybind11/docs/upgrade.rst#stricter-enforcement-of-hidden-symbol-visibility-for-pybind11-modules)), but I believe there should be a better workaround.

**Comment by syncle** [comment] 2018-04-12 17:37
Good catch! I didn't figure out that flag makes an issue. I need to check how this will affect to python binding.

**Comment by Sahloul** [comment] 2018-04-13 00:43
@syncle I think it has no effect on Python binding since in Linux and Windows cases it is not applied, and the binding was doing just fine.

**Comment by qianyizh** [comment] 2018-04-13 05:56
It is from this commit:
https://github.com/IntelVCL/Open3D/commit/db0061a87714b9b0fb88a743e8ec6ce6d1c98fe4

There must be a reason.... let me think...

**Comment by qianyizh** [comment] 2018-04-13 06:13
ummm, the root cause might be a conflict between some libraries linking to ``libc++``, some linking to ``libstdc++``. So if ``visibility=default`` there is an error. OpenCV seems to have a similar issue https://github.com/opencv/opencv/issues/7565

But, this issue for Open3D may have been resolved in https://github.com/IntelVCL/Open3D/commit/9291547e71b1b88531def266ae4430b110e45900

@Sahloul @syncle can you check if the build is still successful after removing this? With two settings: OSX+Clang, and OSX+gcc with OpenMP support (http://www.open3d.org/docs/compilation.html#openmp)

**Comment by Sahloul** [comment] 2018-04-13 06:34
@qianyizh If we remove it, the library compiles with some warnings (see 192.3 and 192.4 from [here](https://travis-ci.org/IntelVCL/Open3D/builds/365485926?utm_source=github_status&utm_medium=notification)). I believe this is only OSX+Clang. But in case of GCC, it is totally OK with Linux. Do we need to test it with Mac as well?

**Comment by qianyizh** [comment] 2018-04-13 06:37
Yes. GCC is the one with problem. See #8 

Also, GCC is the easiest way to enable OpenMP on OSX so we need to test it.

**Comment by Sahloul** [comment] 2018-04-14 11:53
@qianyizh Mac + GCC generated a lot of warning (see [this CI log](https://travis-ci.org/IntelVCL/Open3D/builds/366468598?utm_source=github_status&utm_medium=notification)), but it passed without errors.

So what do you think?

**Comment by qianyizh** [comment] 2018-04-17 05:43
Yes I did it once. See this:
http://www.open3d.org/docs/compilation.html#openmp
Let me try it really quick on my home laptop.

**Comment by qianyizh** [comment] 2018-04-17 06:06
I have checked. Tons of warnings at the end due to inconsistent visibility settings.
But it passes the build.

I guess warnings are better than failure. So let's close this and merge #297 
I will open a separate ticket for remove the compilation warnings.
This will likely to be a visibility setting just for the py3d module.

One additional issue: brew installs gcc-7, we need to update the doc.

**Closed by qianyizh** 2018-04-17 06:06 UTC
Labels: bug, enhancement
