### ISSUE TITLE
handle build warnings

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#366] opened 2018-05-22 20:19 UTC
The VS/Windows build shows a number of warnings:
- warning C4316, 20
- warning C4018, 25
- warning LNK4221, 4

All warnings need to be addressed.
Double check Linux and macOS.

**Comment by takanokage** [comment] 2018-05-22 20:44
yep, good catch.

**Comment by qianyizh** [comment] 2018-05-23 16:31
The OSX warnings see #295 for additional information.

**Comment by qianyizh** [comment] 2018-06-22 08:40
CMake also starts to report warnings:
```
CMake Deprecation Warning at External/GLFW/CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```
We should do code hygiene once in a while.

**Comment by takanokage** [comment] 2018-06-22 15:30
Agreed. We are limited only on the fact that different CMake versions are available on each OS.
For example on Ubuntu:
- 14.04, cmake 2.8.12
- 16.04, cmake 3.5.1
- 17.10, cmake 3.9.1
- 18.04, cmake 3.10.2
- latest cmake 3.12.0-rc1

This means that in order to support all Ubuntu versions we need to adhere to a low version number of CMake which in turn may not allow us to eliminate all warnings everywhere.

**Comment by qianyizh** [comment] 2018-07-05 05:35
This is bugging me. It also affects the compilation speed a lot. Who is going to fix this?

**Comment by qianyizh** [comment] 2018-07-08 00:44
The tons of warnings affect the compilation speed a lot. This is bad. I will take over the ownership.

**Comment by qianyizh** [comment] 2018-07-08 04:39
@syncle there are 27 type conversion warnings in ColorMapOptimization.cpp. You can get this list of warnings by compiling with Visual Studio 2015.

Can you write explicit type conversions and make sure the logic is correct? (I.e., none of the type conversion is not as algorithm designed.)

```
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(104): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(105): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
8>  jquant2.c
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(106): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
8>  jutils.c
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(132): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
8>  Generating Code...
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(344): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(345): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(349): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(350): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(351): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(384): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(385): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(386): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(387): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(388): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(389): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(390): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(391): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
16>  pngread.c
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(488): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(489): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(493): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(496): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(497): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
16>  pngrio.c
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(205): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
9>  D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(236): note: see reference to function template instantiation 'std::tuple<bool,float> three::`anonymous-namespace'::QueryImageIntensity<float>(const three::Image &,const three::`anonymous-namespace'::ImageWarpingField &,const Eigen::Vector3d &,const three::PinholeCameraTrajectory &,int,int)' being compiled
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(208): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(182): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
9>  D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(267): note: see reference to function template instantiation 'std::tuple<bool,float> three::`anonymous-namespace'::QueryImageIntensity<float>(const three::Image &,const Eigen::Vector3d &,const three::PinholeCameraTrajectory &,int,int)' being compiled
9>D:\Research\Open3D\src\Core\ColorMap\ColorMapOptimization.cpp(184): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
```

**Comment by syncle** [comment] 2018-07-08 04:42
working on it.

**Comment by syncle** [comment] 2018-07-08 08:37
As a note, warnings appear in Xcode 8.3. I need to investigate more, but think these lines
```
Scanning dependencies of target Open3D
[ 56%] Linking CXX static library lib/libOpen3D.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libOpen3D.a(PinholeCameraTrajectoryFactory.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libOpen3D.a(PoseGraphFactory.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libOpen3D.a(PinholeCameraTrajectoryFactory.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libOpen3D.a(PoseGraphFactory.cpp.o) has no symbols
```
related to root cause.

**Comment by syncle** [comment] 2018-09-28 03:42
[The issue](https://github.com/IntelVCL/Open3D/issues/366#issuecomment-403272252) had beed addressedin #495. Let me close this issue.

**Closed by syncle** 2018-09-28 03:42 UTC
Labels: bug, high priority
